#!/usr/bin/env bash
# Переключает активный цвет production в Caddy: переписывает сниппет upstream
# и выполняет горячую перезагрузку Caddy (zero-downtime).
# Usage: blue-green-switch.sh <blue|green>
set -Eeuo pipefail

COLOR="${1:?usage: blue-green-switch.sh <blue|green>}"
BASE="${FS_BASE:-/opt/foodscanner}"
SNIPPET="$BASE/caddy/snippets/prod-upstream.caddy"

[[ "$COLOR" == "blue" || "$COLOR" == "green" ]] || { echo "bad color: $COLOR" >&2; exit 2; }

echo "# auto-generated by blue-green-switch.sh" > "$SNIPPET"
echo "reverse_proxy backend-${COLOR}:8080" >> "$SNIPPET"

# Горячая перезагрузка конфигурации без разрыва соединений.
docker exec caddy caddy reload --config /etc/caddy/Caddyfile
echo "Caddy переключён на backend-${COLOR}"
